apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-
namespace: demo-dev

patches:
  - path: patch-replicas.yaml
    target:
      kind: Deployment
      name: demo-app

configMapGenerator:
  - name: app-config
    literals:
      - APP_ENV=dev
      - WELCOME_MESSAGE=hello-from-dev

generatorOptions:
  disableNameSuffixHash: false