apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: stg-
namespace: demo-staging

patches:
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: demo-app

configMapGenerator:
  - name: app-config
    literals:
      - APP_ENV=staging